### PR TITLE
Check for SPF results before sending over emails

### PR DESCRIPTION
**Pull request by arunthampi**
Protects against SPF spoofing

### CODE REVIEW

**Comment by arunthampi** [comment]
apologies for the unsolicited pull request, just checking since by default Mandrill doesn't protect against email spoofing for inbound emails

**Comment by wingrunr21** [comment]
No apologies needed, this is great! Thanks!

**Comment by wingrunr21** [comment]
Changes are in v1.1.3 on rubygems

**Comment by arunthampi** [comment]
nice, just updated my Gemfile <3

**Comment by himynameisjonas** [comment]
Hey, I think it should allow emails with `[:spf][:result] == 'none'`. Or isn't the `none` value a valid one?

**Pull request merged**
